dataset: "clothing1m"
data_path: "./data/clothing1M"
num_class: 14
backbone: "resnet50"
resolution: 224

seed: 0
gpuid: 0
num_workers: 8

stage: 1
frozen: False
pretrained: True
epochs: 5

batch_size: 128

noise_mode: 'real'
noise_ratio: 0.385

class_names: [
  'T-Shirt',
  'Shirt',
  'Knitwear',
  'Chiffon',
  'Sweater',
  'Hoodie',
  'Windbreaker',
  'Jacket',
  'Downcoat',
  'Suit',
  'Shawl',
  'Dress',
  'Vest',
  'Underwear'
]