dataset: "webvision"
data_path: "./data/webvision/"
num_class: 50
backbone: "resnet50"
resolution: 224

seed: 0
gpuid: 0
num_workers: 8

stage: 1
frozen: False
pretrained: True
epochs: 5

batch_size: 128

noise_mode: 'real'
noise_ratio: 0.2

class_names: [
  "tench", 
  "goldfish", 
  "great white shark", 
  "tiger shark", 
  "hammerhead shark", 
  "electric ray", 
  "stingray", 
  "rooster", 
  "hen", 
  "ostrich", 
  "brambling", 
  "goldfinch", 
  "house finch", 
  "junco", 
  "indigo bunting", 
  "American robin", 
  "bulbul", 
  "jay", 
  "magpie", 
  "chickadee", 
  "American dipper", 
  "kite (bird of prey)", 
  "bald eagle", 
  "vulture", 
  "great grey owl", 
  "fire salamander", 
  "smooth newt", 
  "newt", 
  "spotted salamander", 
  "axolotl", 
  "American bullfrog", 
  "tree frog", 
  "tailed frog", 
  "loggerhead sea turtle", 
  "leatherback sea turtle",
  "mud turtle", 
  "terrapin", 
  "box turtle", 
  "banded gecko", 
  "green iguana", 
  "Carolina anole", 
  "desert grassland whiptail lizard", 
  "agama", 
  "frilled-necked lizard", 
  "alligator lizard", 
  "Gila monster", 
  "European green lizard", 
  "chameleon", 
  "Komodo dragon", 
  "Nile crocodile"
]